version: 3.1.{build}
pull_requests:
  do_not_increment_build_number: true
os: Default Azure
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
    cd C:\projects\zendeskapi-v2

    nuget.exe restore
build:
  verbosity: minimal
test: off
#test_script:
#- ps: nunit-console C:\projects\zendeskapi-v2\Tests\bin\Release\Tests.dll /framework:net-4.5
artifacts:
- path: '\ZendeskApi_v2_Package\*.nupkg'
  name: Pakage
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master    